### PR TITLE
Milestone 1: App Features

### PR DESCRIPTION
**Pull request by sntakirutimana72**
# Hello World Milestone 1: App Features

In this milestone I:
- Created an index.html file consisting of one _`<h1>`_ element.
- Added text content to the _`<h1>`_ element.
- Created an index.css file that changes the color of the text content of the _`<h1>`_ element inside the _`index.html`_ file.

### CODE REVIEW

**Review by youmari — CHANGES_REQUESTED** [review]
Hi @sntakirutimana72 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

✔️ Good comments
✔️ Nice set up the `h1` and color


## Required Changes ♻️

- [x] You forgot to add some headers to your the `README.md` file, it would be better to use [this template ](https://github.com/microverseinc/readme-template) and customize it to your preferences
- [x] Your title  and  short summary are not descriptive enough let's try to make them better by explaining what you did exactly, you can revisit the [lesson](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md) here if you want 


_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by sntakirutimana72** [comment]
- Regarding a README.md, it's in fact present unless you're suggesting something to be changed. @youmari

**Comment by youmari** [comment]
> * Regarding a README.md, it's in fact present unless you're suggesting something to be changed. @youmari

yeah I see it  but it will be better to add for example Getting started header

**Comment by youmari** [comment]
> * Regarding a README.md, it's in fact present unless you're suggesting something to be changed. @youmari

Hey @sntakirutimana72 
because you had added it before you created the branch I didn't see it  I'm sorry for that
you can do the other changes and submit again

**Comment by sntakirutimana72** [comment]
So after applying all suggested patches, do I fire up another review request? @youmari

**Comment by youmari** [comment]
> So after applying all suggested patches, do I fire up another review request? @youmari

@sntakirutimana72 yeah go ahead

**Review by ShahierNashaat — APPROVED** [review]
Hi @sntakirutimana72 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Approved :ok_hand: :ok_hand: :ok_hand:

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
